server:
  port: ${PORT_DISCOVERY}

spring:
  application:
    name: discovery

# Eureka server Config
eureka:
  instance:
    hostname: ${HOSTNAME_EUREKA}
  client:
    register-with-eureka: false #because it eureka server no need to register itself
    fetch-registry: false       # no need to fetch registry
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
