# eureka not register
eureka:
  client:
    register-with-eureka: false

server:
  port: ${PORT_GATEWAY}
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: student
          uri: ${URI_STUDENT}
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: ${URI_SCHOOL}
          predicates:
            - Path=/api/v1/schools/**
        - id: customer-service
          uri: ${URI_CUSTOMER}
          predicates:
            - Path=/api/v1/customers/**
# tracing log with zipkin
management:
  tracing:
    sampling:
      probability: 1.0