spring:
  application:
    name: schools
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_SCHOOL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT_SCHOOL}


# eureka register
eureka:
  instance:
    hostname: ${HOSTNAME_EUREKA}
  client:
    service-url:
      defaultZone: ${URI_EUREKA_SERVER_URL}


application:
  config:
    students-url: ${URI_FEIGN_STUDENT}  #student-service url


# tracing log with zipkin
management:
  tracing:
    sampling:
      probability: 1.0